name: ${project.name}
version: ${project.version}
main: me.sizzlemcgrizzle.superblocks.SuperBlocksPlugin
author: sizzlemcgrizzle
api-version: 1.13
description: Modified uses of certain blocks
depend:
  - CLClans
  - CLCore
softdepend:
  - Movecraft
  - WorldGuard
permissions:
  superblocks.admin:
    default: op
commands:
  superblocks:
    description: "Main command for SuperBlocks plugin"

