Prefix: "&8[&6SuperBlocks&8] "
Currency:
  ==: org.bukkit.inventory.ItemStack
  v: 1976
  type: GHAST_TEAR
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: §d§lSpecial Currency

Log_Lag_Over_Milis: 100
Debug: []
Version: 1